### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by ryangjchandler** [ryangjchandler/dab#31]
`dab` is too gen-Z. Need something better, anybody have suggestions?

**Comment by ryangjchandler** [comment]
Here are some of my thoughts, use reactions to vote:

👍 `sliver`
🎉 `dash`
🚀 `crumb`

**Comment by sinnbeck** [comment]
Front End INTeraction = feint

**Comment by ryangjchandler** [comment]
> Front End INTeraction = feint

Oo, very fancy. I'll keep it mind, but I'd like to stick to the synonym's for "small" if possible.

**Comment by ryangjchandler** [comment]
I quite like `crumb` - it's catchy and a nice word to say.
