### ISSUE TITLE
Alpine style properties

### ISSUE THREAD

**Issue by snellingio** [ryangjchandler/dab#35]
Compare the following:

```
events: {
    'window.click.prevent': function (event) {
      this.count++
    },
    click: {
      window: true,
      prevent: true,
      handler(event) {
        this.count++
      }
    }
  },
```

**Comment by ryangjchandler** [comment]
@snellingio I'd rather avoid this / not go down this route just because it adds another level of complexity and another way of doing the same thing, trying to keep the number of ways of doing things limited so that the tool is easy to use.
